### PR TITLE
Refine distance calculation, code, and documentation

### PR DESCRIPTION
**Pull request by mo42**
- Refines distance calculation: `dists[cluster] = tmp.dot(tmp.T)`
- Improve code linting and readme

### CODE REVIEW

**Comment by v-iashin** [comment]
Hi, @mo42 

Thanks for your PR. It is very thorough!

I have one question though. Does it matter in this case actually? `tmp` is a vector `(2,)`.

**Comment by mo42** [comment]
Hi @v-iashin,

> I have one question though. Does it matter in this case actually? `tmp` is a vector `(2,)`.

When I wanted to use your code, it worked only with the changes I made. I'll test this again and show you an example.

**Comment by mo42** [comment]
> I have one question though. Does it matter in this case actually? `tmp` is a vector `(2,)`.

I could not reproduce my issues wit the `tmp.T` vs. `tmp` so I removed these changes. I'm proposing some more code and documentation refinements.

**Comment by v-iashin** [comment]
Ok, thanks.

> I could not reproduce my issues wit the `tmp.T` vs. `tmp`

I can only speculate but perhaps, you were trying to vectorize the computation or using the distance matrix.

**Pull request merged**
